app/views/apiV1.py
import copy
import datetime
import json
import random
import jsons
from typing import List, Tuple, Union, Optional

from flask import Blueprint
from sqlalchemy.orm.exc import NoResultFound

import app.object_models as object_models
import app.utils.ct_search as ct_search
import app.utils.randomCodes as randomCodes
import app.utils.sslyze.simplify_result as sslyze_result_simplify

from config import FlaskConfig
from app.utils.notifications.user_preferences import get_effective_notification_settings, \
    get_effective_active_notification_settings, NotificationChannelOverride, \
    filter_ids_of_notification_settings_user_can_see, mail_add, load_preferences_from_string, \
    CONNECTION_DB_MODELS_TYPES, send_mail_validation
import app.utils.notifications.send as notifications_send


bp = Blueprint('apiV1', __name__)

import flask
from flask import request, jsonify
from loguru import logger

import flask_jwt_extended

import app.utils.db.basic as db_utils
import app.utils.db.advanced as db_utils_advanced
import app.scan_scheduler as scan_scheduler
import app.db_schemas as db_schemas
import app.db_models as db_models
import app.utils.authentication_utils as authentication_utils
import app.actions as actions


@bp.route('/get_next_targets_batch')
def api_get_next_targets_batch():
    return jsonify(scan_scheduler.convert_batch_to_scan_to_list_of_dicts(scan_scheduler.get_batch_to_scan()))


@bp.route('/get_target_id_from_definition', methods=['POST'])
@flask_jwt_extended.jwt_required
def get_target_id(target_def=None):
    if target_def:
        data = target_def
    else:
        data = json.loads(request.data)
    # logger.warning(data)
    data["protocol"] = data.get("protocol", "HTTPS").replace("TlsWrappedProtocolEnum.", "")  # todo: remove this hack
    target = db_utils_advanced.generic_get_create_edit_from_data(db_schemas.TargetSchema, data, get_only=True)
    if not target:
        return "fail", 400
    user_id = authentication_utils.get_user_id_from_current_jwt()

    # validate that the user entered the target definition at least once. Protection against enumaration attack.
    if not actions.can_user_get_target_definition_by_id(target.id, user_id):
        return "fail", 400
    return jsonify({"id": target.id}), 200


@bp.route('/target/<int:target_id>', methods=['GET', 'DELETE'])
@flask_jwt_extended.jwt_required
def api_target_by_id(target_id: int):
    user_id = authentication_utils.get_user_id_from_current_jwt()

    target = actions.get_target_from_id_if_user_can_see(target_id, user_id)
    if target is None:
        return "Target either doesn't exist or you're allowed to see it.", 400

    if request.method == 'DELETE':
        scan_order: db_models.ScanOrder = db_utils_advanced.generic_get_create_edit_from_data(
            db_schemas.ScanOrderSchema,
            {"target_id": target.id, "user_id": user_id},
            get_only=True
        )
        scan_order.active = False
        db_models.db.session.commit()
        db_utils.actions_on_modification(scan_order)

    scan_order = db_utils_advanced.generic_get_create_edit_from_data(db_schemas.ScanOrderSchema,
                                                                     {"target_id": target.id, "user_id": user_id},
                                                                     get_only=True)

    notifications = get_effective_notification_settings(user_id, target_id)

    return jsonify(actions.full_target_settings_to_dict(target, scan_order, notifications))


def additional_channel_email_actions(email_pref: dict, user_id: int) -> bool:
    ADD_NEW_EMAILS_FIELD = "add_new_emails"

    emails_to_be_added = getattr(email_pref, ADD_NEW_EMAILS_FIELD, None)
    if emails_to_be_added:
        try:
            new_mails_or_exception_msg, status_code = mail_add(user_id, emails_to_be_added)
            if status_code != 200:
                raise Exception(new_mails_or_exception_msg)
            delattr(email_pref, ADD_NEW_EMAILS_FIELD)

            new_emails_ids_to_force_enable = [x.id for x in new_mails_or_exception_msg]
            email_pref.force_enabled_ids.extend(new_emails_ids_to_force_enable)
        except Exception as e:
            logger.error(f"Error adding new emails for target: {e}")
            return False

    return True


@bp.route('/add_targets', methods=['POST', 'PUT'])
@bp.route('/add_target', methods=['POST', 'PUT'])
@bp.route('/target', methods=['PUT', 'PATCH'])
@flask_jwt_extended.jwt_required
def api_target():
    user_id = authentication_utils.get_user_id_from_current_jwt()

    data = json.loads(request.data)
    data["target"]["protocol"] = data.get("protocol", "HTTPS").replace("TlsWrappedProtocolEnum.",
                                                                       "")  # todo: remove this hack
    data["target"].pop("id", None)

    target_hostnames = data["target"]["hostname"].split(";")
    target_hostnames = list(map(lambda x: x.strip(), target_hostnames))
    target_hostnames = list(filter(lambda x: len(x), target_hostnames))
    target_hostnames = list(set(target_hostnames))

    target_ids = set()

    for target_hostname in target_hostnames:
        new_target_def = copy.deepcopy(data["target"])
        new_target_def["hostname"] = target_hostname

        target = db_utils_advanced.generic_get_create_edit_from_data(db_schemas.TargetSchema, new_target_def)

        target_ids.add(target.id)

        if data.get("scanOrder"):
            scan_order_def = db_utils.merge_dict_with_copy_and_overwrite(data.get("scanOrder", {}),
                                                                         {"target_id": target.id, "user_id": user_id})
            db_utils_advanced.generic_get_create_edit_from_data(db_schemas.ScanOrderSchema, scan_order_def)

    if data.get("notifications"):
        set_notification_settings_raw_multiple_target_ids(user_id, target_ids, data.get("notifications"))

    return f'Inserted {len(target_ids)} targets', 200
    # return api_target_by_id(target.id)  # todo: reenable this


@bp.route('/test_jsons', methods=['POST'])
def test_jsons():
    data = jsons.loads(request.data, NotificationChannelOverride)
    return jsons.dumps(data), 200


@bp.route('/add_scan_order', methods=['POST'])
@flask_jwt_extended.jwt_required
def api_add_scan_order():
    data = json.loads(request.data)
    schema = db_schemas.ScanOrderSchema(session=db_models.db)
    # todo deduplicate
    # todo validation
    data["user_id"] = random.randrange(100000)  # todo: make dynamic (from server side)
    result = schema.load(data)
    db_models.db.session.add(result)
    db_models.db.session.commit()
    db_utils.actions_on_modification(result)
    return repr(result)


@bp.route('/enable_target_scan/<int:target_id>', methods=['GET'])
@flask_jwt_extended.jwt_required
def api_enable_target_scan(target_id: int):
    user_id = authentication_utils.get_user_id_from_current_jwt()

    target = actions.get_target_from_id_if_user_can_see(target_id, user_id)
    if target is None:
        return "Target either doesn't exist or you're allowed to see it.", 400

    scan_order: db_models.ScanOrder = db_utils_advanced.generic_get_create_edit_from_data(
        db_schemas.ScanOrderSchema,
        {"target_id": target.id, "user_id": user_id},
        get_only=True
    )
    scan_order.active = True
    db_models.db.session.commit()
    db_utils.actions_on_modification(scan_order)
    return "ok", 200


@bp.route('/login', methods=['POST'])
def api_login():
    if not request.is_json:
        return jsonify({"msg": "Missing JSON in request"}), 400

    username = request.json.get('username', None)
    password = request.json.get('password', None)

    return action_login(username, password)


def action_login(username, password) -> Tuple[str, int]:
    USERNAME_PASSWORD_NOT_FOUND_MSG = "Bad username or password"
    msg = ""

    if not username:
        msg += "Missing username parameter. "
    if not password:
        msg += "Missing password parameter. "
    if len(msg):
        return jsonify({"msg": msg}), 400

    # todo: validate inputs

    res = db_models.db.session \
        .query(db_models.User) \
        .filter(db_models.User.username == username) \
        .first()

    if res is None:
        return jsonify({"msg": USERNAME_PASSWORD_NOT_FOUND_MSG}), 401

    # todo: check bogus password even when username doesn't exist to eliminate timing attack
    res: db_models.User
    is_password_valid: bool = authentication_utils.check_password(res.password_hash, password)

    if not is_password_valid:
        return jsonify({"msg": USERNAME_PASSWORD_NOT_FOUND_MSG}), 401

    identity = {"id": res.id, "username": res.username}
    access_token = flask_jwt_extended.create_access_token(identity=identity, fresh=True)
    refresh_token = flask_jwt_extended.create_refresh_token(identity=identity)
    response_object = jsonify(access_token=access_token)
    response_object: flask.Response

    flask_jwt_extended.set_refresh_cookies(response_object, refresh_token)

    # response_object.set_cookie("refresh_token", refresh_token,
    #                            max_age=FlaskConfig.JWT_REFRESH_TOKEN_EXPIRES.total_seconds(),
    #                            secure=True, httponly=True,
    #                            domain=None,  # todo
    #                            path='/')  # todo

    return response_object, 200


@bp.route('/register', methods=['POST'])
def api_register():
    data = json.loads(request.data)
    # todo: validation
    exists_username = db_models.db.session \
        .query(db_models.User.id) \
        .filter(db_models.User.username == data["username"]) \
        .first()

    if exists_username is not None:
        return jsonify({"msg": "Username already exists"}), 400  # is there way avoid username enumeration?

    data["password_hash"] = authentication_utils.generate_password_hash(data["password"])
    data.pop("password")

app/views/other.py
from flask import Blueprint
bp = Blueprint('otherRoutes', __name__)

from flask import render_template


@bp.route('/')
@bp.route('/index')
def index():
    # test_arg = [{"title": "title1", "content": "content1"}, {"title": "title2", "content": "content2"}]
    test_arg = []
    return render_template('index.html', title='Test index page', test_arg=test_arg)


@bp.route('/dashboard')
def dashboard_index():
    return render_template('index.html', title='Dashboard', test_arg=[])


@bp.route('/dashboard/login')
def dashboard_login():
    return render_template('index.html', title='Dashboard login', test_arg=[])


@bp.route('/debug/html/batch_direct_scan')
def debug_batch_direct_scan_html():
    return render_template('debug_html/batch_direct_scan.html')


@bp.route('/debug/<string:domain>')
@bp.route('/debug/')
def debug_overview(domain="borysek.eu"):
    return render_template('debug_overview.html', domain=domain)

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>{{ title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Load required Bootstrap and BootstrapVue CSS -->
        <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap/dist/css/bootstrap.css" />
        <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css" />

        <!-- Load polyfills to support older browsers -->
        <script src="https://polyfill.io/v3/polyfill.min.js?features=es2015%2CIntersectionObserver" crossorigin="anonymous"></script>


        <!-- development version, includes helpful console warnings. todo: replace -->
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

        <!-- Load Vue followed by BootstrapVue -->
        <!-- <script src="https://unpkg.com/vue@latest/dist/vue.min.js"></script> -->
        <script src="https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>

        <!-- Load the following for BootstrapVueIcons support -->
        <script src="https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue-icons.js"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha384-v8BU367qNbs/aIZIxuivaU55N5GPF89WBerHoGA4QTcbUjYiLQtKdrfXnqAcXyTv" crossorigin="anonymous">

    </head>
    <body>
        <div>
            Menu:
            <a href="{{ url_for('otherRoutes.index') }}">Homepage</a>
            <i class="fas fa-biohazard"></i>
            <span class="fas fa-camera"></span>
        </div>
        <div>
            <h1>Title: {{ title }}</h1>
        </div>
        {% block content %}{% endblock %}

        <div>
          <b-img src="https://picsum.photos/1024/400/?image=41" fluid alt="Responsive image"></b-img>
        </div>

    </body>
</html>

app/templates/debug_overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Debug overview</title>
</head>
<body>

DB helpers
<ul>
    <li><a href="{{ url_for('apiDebug.debug_db_initialize_from_file') }}">debug_db_initialize_from_file</a></li>
    <li><a href="{{ url_for('apiDebug.debug_db_get_all') }}">debug_db_get_all</a></li>
    <li><a href="{{ url_for('apiDebug.debug_db_backdate_last_enqued') }}">debug_db_backdate_last_enqued</a></li>
    <li><a href="{{ url_for('apiDebug.debug_domain_to_target_string', domain=domain) }}">debug_domain_to_target_string</a></li>
</ul>

Direct scans
<ul>
    <li><a href="{{ url_for('apiDebug.debug_dns_resolve_domain', domain=domain) }}">debug_dns_resolve_domain</a></li>
    <li><a href="{{ url_for('apiDebug.debug_ct_get_subdomains', domain=domain) }}">debug_ct_get_subdomains</a></li>
    <li><a href="{{ url_for('apiDebug.debug_sslyze_get_direct_scan', domain=domain) }}">debug_sslyze_get_direct_scan</a></li>
    <li><a href="{{ url_for('otherRoutes.debug_batch_direct_scan_html') }}">debug_batch_direct_scan_html</a></li>
</ul>

Endpoints
<ul>
    <li><a href="{{ url_for('apiV1.api_get_next_targets_batch') }}">api_get_next_targets_batch</a></li>
</ul>


</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for it in test_arg %}
        <p>{{ it.title }}: {{ it.content }}</p>
    {% endfor %}
{% endblock %}